/**
 * client.ts
 * ----------
 * Browser-side Supabase client for VIZORIA AI.
 *
 * Responsibility:
 *   - Initialise a singleton Supabase client that runs in the browser.
 *   - Used by client-side code that triggers OAuth redirects, listens to
 *     auth state changes, or performs real-time subscriptions.
 *
 * Security note:
 *   - Only the anon key is used here. The anon key is safe to expose in the
 *     browser because Row Level Security (RLS) on the database enforces what
 *     an anonymous or authenticated user may actually read/write.
 *   - The service-role key MUST NEVER be placed in this file.
 */

import { createBrowserClient } from "@supabase/ssr";
import type { Database } from "@/types/database"; // generated by `supabase gen types`

// Vite / TanStack Start exposes env vars through import.meta.env.
// These values are public — they are embedded in the JS bundle.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "[VIZORIA] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY environment variables."
  );
}

// createBrowserClient handles cookie-based session persistence automatically
// using the @supabase/ssr package — the recommended approach for TanStack Start.
export const supabaseClient = createBrowserClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY
);

/**
 * Convenience: returns the currently authenticated user from the local session.
 * For authoritative checks, always use the server-side `getCurrentUser()` instead,
 * because the browser session can be spoofed.
 */
export async function getClientUser() {
  const {
    data: { user },
    error,
  } = await supabaseClient.auth.getUser();

  if (error) return null;
  return user;
}
